{
 "title": "Prusa MKx / Overview",
 "description": "Dashboard for Prusa MK3.5(S) / MK3.9(S) / MK4(S)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   { "name": "DS_LOKI", "label": "Loki", "query": "loki" },
   {
    "name": "printer_address",
    "label": "Printer",
    "query": {
     "query": "label_values(prusa_up{printer_model=~\"MK.*\"},printer_address)"
    }
   },
   {
    "name": "printer_name",
    "label": "Name",
    "query": {
     "query": "label_values(prusa_info{printer_address=\"$printer_address\"},printer_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Printed file",
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{printer_address=\"$printer_address\"}",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Printer Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(printer_name) (prusa_info{printer_address=\"$printer_address\"})",
     "legendFormat": "{{printer_job_name}}"
    }
   ]
  },
  {
   "title": "Printer Model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(printer_model) (prusa_info{printer_address=\"$printer_address\"})",
     "legendFormat": "{{printer_job_name}}"
    }
   ]
  },
  {
   "title": "Filament",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by(printer_filament) (prusa_material_info{printer_address=\"$printer_address\"})",
     "legendFormat": "{{printer_filament}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg by(printer_state) (prusa_status_info{printer_address=\"$printer_address\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Progress",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_printing_progress_ratio{printer_address=\"$printer_address\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_printing_time_remaining_seconds{printer_address=\"$printer_address\", printer_job_name!=\"\"} ",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Print Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_print_speed_ratio{printer_address=\"$printer_address\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Print Flow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_print_flow_ratio{printer_address=\"$printer_address\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 14, "x": 5, "y": 3 } },
  {
   "title": "MMU status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(printer_name) (prusa_mmu{printer_address=\"$printer_address\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nozzle Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "mm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_nozzle_size_meters{printer_address=\"$printer_address\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature - Nozzle",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "(avg by (printer_address) (prusa_temp_noz{printer_address=\"$printer_address\"}) and on(printer_address) (changes(prusa_temp_noz{printer_address=\"$printer_address\"}[30s]) > 0)) or (avg by (printer_address) (prusa_temperature_celsius{printer_address=\"$printer_address\",printer_heated_element=\"tool0\"}))",
     "legendFormat": "Actual"
    },
    {
     "expr": "(avg by (printer_address) (prusa_ttemp_noz{printer_address=\"$printer_address\"}) and on(printer_address) (changes(prusa_ttemp_noz{printer_address=\"$printer_address\"}[30s]) > 0)) or (avg by (printer_address) (prusa_temperature_target_celsius{printer_address=\"$printer_address\",printer_heated_element=\"tool0\"}))",
     "legendFormat": "Target"
    }
   ]
  },
  {
   "title": "Temperature - Heatbed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "(avg by (printer_address) (prusa_temp_bed{printer_address=\"$printer_address\"}) and on(printer_address) (changes(prusa_temp_bed{printer_address=\"$printer_address\"}[30s]) > 0)) or (avg by (printer_address) (prusa_temperature_celsius{printer_address=\"$printer_address\",printer_heated_element=\"bed\"}))",
     "legendFormat": "Actual"
    },
    {
     "expr": "(avg by (printer_address) (prusa_ttemp_bed{printer_address=\"$printer_address\"}) and on(printer_address) (changes(prusa_ttemp_bed{printer_address=\"$printer_address\"}[30s]) > 0)) or (avg by (printer_address) (prusa_temperature_target_celsius{printer_address=\"$printer_address\",printer_heated_element=\"bed\"}))",
     "legendFormat": "Target"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "prusa_cpu_usage{printer_address=\"$printer_address\"}",
     "legendFormat": "%"
    },
    { "expr": "vector(100)", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_status_info{printer_address=\"$printer_address\"} == 4",
     "legendFormat": "{{printer_job_name}}"
    }
   ]
  },
  {
   "title": "Fan speeds",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg by (fan) (prusa_fan_measured{printer_address=\"$printer_address\"}) and on(printer_address) (changes(prusa_fan_measured{printer_address=\"$printer_address\"}[30s]) > 0)) or (avg by (fan) (prusa_fan_speed_rpm{printer_address=\"$printer_address\"}))",
     "legendFormat": "{{fan}}"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg by (printer_address) (prusa_temp_noz{printer_address=\"$printer_address\"}) and on(printer_address) (changes(prusa_temp_noz{printer_address=\"$printer_address\"}[30s]) > 0)) or (avg by (printer_address) (prusa_temperature_celsius{printer_address=\"$printer_address\",printer_heated_element=\"tool0\"}))",
     "legendFormat": "Nozzle"
    },
    {
     "expr": "prusa_temp_hbr{printer_address=\"$printer_address\"}",
     "legendFormat": "Heatbreak "
    },
    {
     "expr": "(avg by (printer_address) (prusa_temp_bed{printer_address=\"$printer_address\"}) and on(printer_address) (changes(prusa_temp_bed{printer_address=\"$printer_address\"}[30s]) > 0)) or (avg by (printer_address) (prusa_temperature_celsius{printer_address=\"$printer_address\",printer_heated_element=\"bed\"}))",
     "legendFormat": "Heatbed"
    },
    {
     "expr": "prusa_temp_mcu{printer_address=\"$printer_address\"}",
     "legendFormat": "MCU"
    },
    {
     "expr": "prusa_temp_brd{printer_address=\"$printer_address\"}",
     "legendFormat": "Buddy board"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "prusa_heap_total{printer_address=\"$printer_address\"} - prusa_heap_free{printer_address=\"$printer_address\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "prusa_heap_total{printer_address=\"$printer_address\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Power consumption (!)",
   "type": "timeseries",
   "description": "Metrics WIP",
   "gridPos": { "h": 9, "w": 7, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "240 - abs(prusa_curr_inp{printer_address=\"$printer_address\"})  * prusa_volt_bed{printer_address=\"$printer_address\"}",
     "legendFormat": "Watts"
    }
   ]
  },
  {
   "title": "Sensors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prusa_fsensor_f{printer_address=\"$printer_address\"}",
     "legendFormat": "Filament Sensor"
    },
    {
     "expr": "prusa_loadcell_value{printer_address=\"$printer_address\"}",
     "legendFormat": "Loadcell"
    },
    {
     "expr": "prusa_fsensor_raw{printer_address=\"$printer_address\"}",
     "legendFormat": "Filament Sensor"
    }
   ]
  },
  {
   "title": "Network activity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(prusa_eth_out_sent{printer_address=\"$printer_address\"}[$__rate_interval])",
     "legendFormat": "Ethernet Out"
    },
    {
     "expr": "rate(prusa_eth_in_recv{printer_address=\"$printer_address\"}[$__rate_interval])",
     "legendFormat": "Ethernet In"
    },
    {
     "expr": "rate(prusa_esp_in_recv{printer_address=\"$printer_address\"}[$__rate_interval])",
     "legendFormat": "Wifi In"
    },
    {
     "expr": "rate(prusa_esp_out_sent{printer_address=\"$printer_address\"}[$__rate_interval])",
     "legendFormat": "Wifi Out"
    }
   ]
  },
  {
   "title": "G-Code for UDP sent",
   "type": "stat",
   "description": "There was an error while sending metrics activation G-Code to the printer OR it's deactivated ",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "mm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_udp_metrics_gcode_sent{printer_address=\"$printer_address\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}