{
 "title": "Prusa XL / Overview",
 "description": "Dashboard for Prusa XL",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   { "name": "DS_LOKI", "label": "Loki", "query": "loki" },
   {
    "name": "printer_address",
    "label": "Printer",
    "query": {
     "query": "label_values(prusa_up{printer_model=~\"XL\"},printer_address)"
    }
   },
   {
    "name": "printer_name",
    "label": "Name",
    "query": {
     "query": "label_values(prusa_info{printer_address=\"$printer_address\"},printer_name)"
    }
   },
   {
    "name": "active_extruder",
    "query": {
     "query": "query_result(max(prusa_active_extruder{printer_address=\"$printer_address\"})  or vector(-2))"
    }
   },
   {
    "name": "active_extruder_adjusted",
    "query": {
     "query": "query_result(max(prusa_active_extruder{printer_address=\"$printer_address\"}) +1 or vector(-1))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Printed file",
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{printer_address=\"$printer_address\"}",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Printer Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(printer_name) (prusa_info{printer_address=\"$printer_address\"})",
     "legendFormat": "{{printer_job_name}}"
    }
   ]
  },
  {
   "title": "Printer Model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(printer_model) (prusa_info{printer_address=\"$printer_address\"})",
     "legendFormat": "{{printer_job_name}}"
    }
   ]
  },
  {
   "title": "Filament",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by(printer_filament) (prusa_material_info{printer_address=\"$printer_address\"})",
     "legendFormat": "{{printer_filament}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg by(printer_state) (prusa_status_info{printer_address=\"$printer_address\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Progress",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_printing_progress_ratio{printer_address=\"$printer_address\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_printing_time_remaining_seconds{printer_address=\"$printer_address\", printer_job_name!=\"\"} ",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Print Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(printer_address) (prusa_print_speed_ratio{printer_address=\"$printer_address\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Print Flow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(printer_address) (prusa_print_flow_ratio{printer_address=\"$printer_address\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 14, "x": 5, "y": 3 } },
  {
   "title": "MMU status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(printer_name) (prusa_mmu{printer_address=\"$printer_address\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nozzle Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "mm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(printer_address) (prusa_nozzle_size_meters{printer_address=\"$printer_address\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature - Loaded Nozzle ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "min by (n)(prusa_temp_noz{printer_address=\"$printer_address\", n=\"$active_extruder\"})",
     "legendFormat": "Actual"
    },
    {
     "expr": "max by (n)(prusa_ttemp_noz{printer_address=\"$printer_address\", n=\"$active_extruder\"}) ",
     "legendFormat": "Target"
    }
   ]
  },
  {
   "title": "Temperature - Heatbed",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "(avg by (printer_address) (prusa_temp_bed{printer_address=\"$printer_address\"}) and on(printer_address) (changes(prusa_temp_bed{printer_address=\"$printer_address\"}[30s]) > 0)) or (avg by (printer_address) (prusa_temperature_celsius{printer_address=\"$printer_address\",printer_heated_element=\"bed\"}))",
     "legendFormat": "Actual"
    },
    {
     "expr": "(avg by (printer_address) (prusa_ttemp_bed{printer_address=\"$printer_address\"}) and on(printer_address) (changes(prusa_ttemp_bed{printer_address=\"$printer_address\"}[30s]) > 0)) or (avg by (printer_address) (prusa_temperature_target_celsius{printer_address=\"$printer_address\",printer_heated_element=\"bed\"}))",
     "legendFormat": "Target"
    }
   ]
  },
  {
   "title": "Loaded Tool",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vector($active_extruder_adjusted)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Adjust Z-Axis",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_adj_z{printer_address=\"$printer_address\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_status_info{printer_address=\"$printer_address\"} == 4",
     "legendFormat": "{{printer_job_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "prusa_cpu_usage{printer_address=\"$printer_address\"}",
     "legendFormat": "%"
    },
    { "expr": "vector(100)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Fan speeds",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg by (fan) (prusa_fan_measured{printer_address=\"$printer_address\"}) and on(printer_address) (changes(prusa_fan_measured{printer_address=\"$printer_address\"}[30s]) > 0)) or (avg by (fan) (prusa_fan_speed_rpm{printer_address=\"$printer_address\"}))",
     "legendFormat": "{{fan}}"
    },
    {
     "expr": "prusa_fan_measured{printer_address=\"$printer_address\", fan=\"enclosure\"}",
     "legendFormat": "enclosure"
    }
   ]
  },
  {
   "title": "Power consumption (!)",
   "type": "timeseries",
   "description": "Validity of data need more testing",
   "gridPos": { "h": 11, "w": 5, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "abs((prusa_curr_inp{printer_address=\"$printer_address\"}* 24)) ",
     "legendFormat": "Watts"
    },
    {
     "expr": "sum(prusa_bed_curr{printer_address=\"$printer_address\"})* sum(prusa_24VVoltage{printer_address=\"$printer_address\"})",
     "legendFormat": "Bed"
    },
    {
     "expr": "prusa_splitter_5V_current{printer_address=\"$printer_address\"}*prusa_5VVoltage{printer_address=\"$printer_address\"}",
     "legendFormat": "5V Rail"
    },
    {
     "expr": "sum(prusa_dwarf_heat_curr{printer_address=\"$printer_address\"} < 50 or vector(0))  * sum(prusa_24VVoltage{printer_address=\"$printer_address\"})",
     "legendFormat": "Dwarfs"
    }
   ]
  },
  {
   "title": "Temperature - All Nozzles",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "min by (n)(prusa_temp_noz{printer_address=\"$printer_address\"})",
     "legendFormat": "Nozzle - {{n}}"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "prusa_heap_total{printer_address=\"$printer_address\"} - prusa_heap_free{printer_address=\"$printer_address\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "prusa_heap_total{printer_address=\"$printer_address\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg by (printer_address) (prusa_temp_noz{printer_address=\"$printer_address\"}) and on(printer_address) (changes(prusa_temp_noz{printer_address=\"$printer_address\"}[30s]) > 0)) or (avg by (printer_address) (prusa_temperature_celsius{printer_address=\"$printer_address\",printer_heated_element=\"tool0\"}))",
     "legendFormat": "Nozzle"
    },
    {
     "expr": "(avg by (printer_address) (prusa_temp_bed{printer_address=\"$printer_address\"}) and on(printer_address) (changes(prusa_temp_bed{printer_address=\"$printer_address\"}[30s]) > 0)) or (avg by (printer_address) (prusa_temperature_celsius{printer_address=\"$printer_address\",printer_heated_element=\"bed\"}))",
     "legendFormat": "Heatbed"
    },
    {
     "expr": "prusa_temp_mcu{printer_address=\"$printer_address\"}",
     "legendFormat": "MCU"
    },
    {
     "expr": "prusa_temp_brd{printer_address=\"$printer_address\"}",
     "legendFormat": "Buddy board"
    },
    {
     "expr": "prusa_chamber_temp{printer_address=\"$printer_address\"}",
     "legendFormat": "Chamber"
    }
   ]
  },
  {
   "title": "Network activity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(prusa_eth_out_sent{printer_address=\"$printer_address\"}[$__rate_interval])",
     "legendFormat": "Ethernet Out"
    },
    {
     "expr": "rate(prusa_eth_in_recv{printer_address=\"$printer_address\"}[$__rate_interval])",
     "legendFormat": "Ethernet In"
    },
    {
     "expr": "rate(prusa_esp_in_recv{printer_address=\"$printer_address\"}[$__rate_interval])",
     "legendFormat": "Wifi In"
    },
    {
     "expr": "rate(prusa_esp_out_sent{printer_address=\"$printer_address\"}[$__rate_interval])",
     "legendFormat": "Wifi Out"
    }
   ]
  }
 ]
}